"""Init

Revision ID: 7e1a16c6bde5
Revises: 13a665550bcc
Create Date: 2023-10-09 10:37:15.323879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1a16c6bde5'
down_revision: Union[str, None] = '13a665550bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthday', sa.DateTime(), nullable=False))
    op.drop_index('ix_contacts_birthdate', table_name='contacts')
    op.create_index(op.f('ix_contacts_birthday'), 'contacts', ['birthday'], unique=False)
    op.drop_column('contacts', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthdate', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_contacts_birthday'), table_name='contacts')
    op.create_index('ix_contacts_birthdate', 'contacts', ['birthdate'], unique=False)
    op.drop_column('contacts', 'birthday')
    # ### end Alembic commands ###
